#!/bin/bash
# fetch-secrets.sh
# Fetches HaloPSA MCP configuration from Azure Key Vault and writes .env
# Requires: Azure CLI, VM managed identity with Key Vault Secrets User role
# Usage: ./fetch-secrets.sh [--vault <vault-name>] [--domain <public-domain>]

set -euo pipefail

VAULT="${KEYVAULT_NAME:-HaloSecrets}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

# Allow overrides via arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --vault) VAULT="$2"; shift 2 ;;
        --domain) OVERRIDE_DOMAIN="$2"; shift 2 ;;
        *) echo "Unknown argument: $1"; exit 1 ;;
    esac
done

echo "Fetching secrets from Key Vault: $VAULT"

# Authenticate via managed identity
az login --identity --output none 2>/dev/null || {
    echo "ERROR: Failed to authenticate via managed identity."
    echo "Ensure the VM has a system-assigned managed identity with Key Vault Secrets User role on $VAULT."
    exit 1
}

fetch_secret() {
    local secret_name="$1"
    az keyvault secret show \
        --vault-name "$VAULT" \
        --name "$secret_name" \
        --query "value" \
        --output tsv 2>/dev/null || {
        echo "ERROR: Could not fetch secret '$secret_name' from vault '$VAULT'." >&2
        exit 1
    }
}

echo "Fetching configuration..."

HMCP_HALO_URL=$(fetch_secret "halopsa-mcp-halo-url")
HMCP_HALO_CLIENT_ID=$(fetch_secret "halopsa-mcp-client-id")
HMCP_HALO_TENANT=$(fetch_secret "halopsa-mcp-tenant")
HMCP_ENCRYPTION_KEY=$(fetch_secret "halopsa-mcp-encryption-key")
HMCP_DB_PASSWORD=$(fetch_secret "halopsa-mcp-db-password")

# Public domain: Key Vault value unless overridden via --domain argument
if [[ -n "${OVERRIDE_DOMAIN:-}" ]]; then
    HMCP_PUBLIC_DOMAIN="$OVERRIDE_DOMAIN"
else
    HMCP_PUBLIC_DOMAIN=$(fetch_secret "halopsa-mcp-public-domain")
fi

echo "Writing .env..."

cat > "$ENV_FILE" <<EOF
# Generated by fetch-secrets.sh — do not edit manually
HMCP_HALO_URL=${HMCP_HALO_URL}
HMCP_HALO_CLIENT_ID=${HMCP_HALO_CLIENT_ID}
HMCP_HALO_CLIENT_SECRET=
HMCP_HALO_TENANT=${HMCP_HALO_TENANT}
HMCP_ENCRYPTION_KEY=${HMCP_ENCRYPTION_KEY}
HMCP_PUBLIC_DOMAIN=${HMCP_PUBLIC_DOMAIN}
HMCP_HOST=0.0.0.0
HMCP_PORT=8080
HMCP_DB_USER=hmcp
HMCP_DB_PASSWORD=${HMCP_DB_PASSWORD}
HMCP_DB_NAME=hmcp
HMCP_SEMANTIC_SEARCH=false
HMCP_EMBEDDER_URL=http://hmcp-embedder:8081
HMCP_EMBED_PROVIDER=local
HMCP_EMBED_MODEL=BAAI/bge-base-en-v1.5
EOF

chmod 600 "$ENV_FILE"
echo ".env written successfully."
