[package]
name = "hmcp-db-sqlite"
edition.workspace = true
version.workspace = true

[dependencies]
hmcp-common = { path = "../hmcp-common" }
aes-gcm = "0.10"
async-trait = "0.1"
base64 = "0.22"
rusqlite = { version = "0.32", features = ["bundled"] }
sha2 = "0.10"
tokio = { version = "1", features = ["rt"] }
zeroize = { version = "1", features = ["derive"] }
